### ISSUE TITLE
Uncaught TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by CatoMaior** [atom-community/atom-ide-hyperclick#125]
Steps to reproduce
1. Install `atom-ide-base` package
2. Install `atom-ide-debugger` package
3. Try to put break point in your code

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [atom-ide-hyperclick](https://github.com/atom-ide-community/atom-ide-hyperclick) package 1.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'current' of undefined

```
At /home/catomaior/.atom/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:250

TypeError: Cannot read property 'current' of undefined
    at Pj (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:250:24)
    at Tj (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:250:104)
    at Lj (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:243:163)
    at Jg (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:237:175)
    at lk (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
    at /packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:289:301
    at Xj (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:244:244)
    at tk (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:289:287)
    at Object.exports.render (/packages/atom-ide-hyperclick/node_modules/react-dom/cjs/react-dom.production.min.js:296:69)
    at HTMLElement.connectedCallback (/packages/atom-ide-debugger/node_modules/@atom-ide-community/nuclide-commons-ui/ReactMountRootElement.js:64:23)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:152:22)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1171250)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1172691)
    at Pane.setActiveItem (/usr/share/atom/resources/app/static/<embedded>:11:456810)
    at Pane.addItem (/usr/share/atom/resources/app/static/<embedded>:11:460224)
    at DebuggerLayoutManager._appendItemToDock (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:294:16)
    at DebuggerLayoutManager._addPaneContainerToWorkspace (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:648:10)
    at DebuggerLayoutManager.showDebuggerViews (/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:593:44)
    at /packages/atom-ide-debugger/dist/main.js:412:24)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350343)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348818)
    at BreakpointDisplayController._handleGutterClick (/packages/atom-ide-debugger/dist/BreakpointDisplayController.js:316:25)
```

### Commands

```
     -1:22.2.0 tree-view:toggle (input.hidden-input)
     -1:21.4.0 application:reopen-project (div#add-projects-view.)
     -0:06.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-gdb-debugger 0.2.2 
atom-ide-base 2.3.5 
atom-ide-datatip 0.24.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.9 
atom-ide-markdown-service 2.0.0 
atom-ide-outline 2.0.0 
atom-ide-signature-help 0.15.3 
busy-signal 2.0.1 
ftp-remote-edit 0.18.1 
Hydrogen 2.14.7 
ide-cpp 0.1.0 
intentions 1.1.5 
language-generic-config 1.4.0 
linter 3.3.0 
linter-ui-default 3.2.5 
select-rectangle 1.0.2 
```

**Comment by UziTech** [comment]
It looks like this is an issue for `atom-ide-debugger`. the stack trace says the error is coming from `(/packages/atom-ide-debugger/dist/ui/DebuggerLayoutManager.js:294:16)`
