### ISSUE TITLE
Failed to activate the atom-ide-hyperclick package

### ISSUE THREAD

**Issue by des2154022** [atom-community/atom-ide-hyperclick#145]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-ide-hyperclick](https://github.com/atom-ide-community/atom-ide-hyperclick) package 1.0.11

### Stack Trace

Failed to activate the atom-ide-hyperclick package

```
At Cannot find module './internal/Observable'
Require stack:
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\node_modules\rxjs\dist\cjs\index.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\HyperclickForTextEditor.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\Hyperclick.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\main.js
- C:\Users\alexander\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html

Error: Cannot find module './internal/Observable'
Require stack:
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\node_modules\rxjs\dist\cjs\index.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\HyperclickForTextEditor.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\Hyperclick.js
- C:\Users\alexander\.atom\packages\atom-ide-hyperclick\lib\main.js
- C:\Users\alexander\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js:17:20)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js:357:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-ide-hyperclick/lib/HyperclickForTextEditor.js:16:14)
    at /packages/atom-ide-hyperclick/lib/HyperclickForTextEditor.js:488:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-ide-hyperclick/lib/Hyperclick.js:14:33)
    at /packages/atom-ide-hyperclick/lib/Hyperclick.js:104:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-clickable-plugin 1.2.0 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
build 0.70.0 
busy-signal 2.0.1 
Hydrogen 2.16.3 
ide-html 0.7.0 
ide-python 1.8.0 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
my-package 0.0.0 
```

**Comment by UziTech** [comment]
Uninstall and reinstall
