### ISSUE TITLE
Failed to activate the atom-ide-hyperclick package

### ISSUE THREAD

**Issue by LeszekNie** [atom-community/atom-ide-hyperclick#147]
[Enter steps to reproduce:]

1. Application started automatically after brownout, it works well when started by user click on app icon.
2. Similar cases for every other Electron based app (VSCode etc.)

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.2
**Thrown From**: [atom-ide-hyperclick](https://github.com/atom-ide-community/atom-ide-hyperclick) package 1.0.11

### Stack Trace

Failed to activate the atom-ide-hyperclick package

```
At EACCES: permission denied, open '/Users/snowold/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js'

Error: EACCES: permission denied, open '/Users/snowold/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Proxy.readFileSync (fs.js:342:35)
    at Proxy.fs.readFileSync (electron/js2c/asar.js:542:40)
    at compileFileAtPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150787)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153451)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeMap.js:7:24)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeMap.js:21:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeAll.js:4:18)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/mergeAll.js:12:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/concatAll.js:4:18)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/operators/concatAll.js:10:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
clickable-npm-scripts 3.9.0 
emmet 2.4.3 
ide-rust 1.1.1 
ide-svelte-2 0.2.2 
intentions 2.1.1 
last-cursor-position 1.2.0 
linter 3.4.0 
linter-ui-default 3.4.1 
platformio-ide-terminal 2.10.1 
remote-ftp 2.2.4 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
```

**Comment by UziTech** [comment]
Looks like a permission issue on your computer. Nothing we can do about it in the code.

**Comment by LeszekNie** [comment]
That is right, but the permission kicks in only after reboot. When started from clicking on icon, the file permission is perfectly good. To me it looks like the Electron problem, but the Atom asked for creating the issue and I did. I am going to dig a little bit here. And yes, there's nothing you can do in the Atom code.
