### ISSUE TITLE
Failed to activate the atom-ide-hyperclick package

### ISSUE THREAD

**Issue by MC71-3** [atom-community/atom-ide-hyperclick#148]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [atom-ide-hyperclick](https://github.com/atom-ide-community/atom-ide-hyperclick) package 1.0.11

### Stack Trace

Failed to activate the atom-ide-hyperclick package

```
At Cannot find module './util/isFunction'
Require stack:
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Subscriber.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Observable.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/HyperclickForTextEditor.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/Hyperclick.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module './util/isFunction'
Require stack:
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Subscriber.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Observable.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/HyperclickForTextEditor.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/Hyperclick.js
- /Users/mcoulouc/.atom/packages/atom-ide-hyperclick/lib/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Subscriber.js:19:20)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Subscriber.js:202:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Observable.js:4:20)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/internal/Observable.js:106:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149207)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js:17:20)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/dist/cjs/index.js:357:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
```

### Commands

```
  8x -5:20.5.0 core:backspace (input.hidden-input)
     -0:48.6.0 core:paste (input.input-text.native-key-bindings)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 0.0.0 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.0.0 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
ide-python 1.9.7 
ide-r 0.1.8 
```

**Comment by UziTech** [comment]
Reinstall and it should work
