### ISSUE TITLE
Uncaught TypeError: log4js is not a function

### ISSUE THREAD

**Issue by idleberg** [atom-community/atom-ide-hyperclick#2]
I've just upgraded my own Hyperclick-consuming package to use this new package. Once installed, the following error message will pop up when holding <kdb>Cmd</kbd> and moving the mouse over a clickable string. Note that the mentioned `log4js` package is installed in the `node_modules` folder of `atom-ide-community`!

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-ide-hyperclick](https://github.com/atom-ide-community/atom-ide-hyperclick) package 1.0.0

### Stack Trace

Uncaught TypeError: log4js is not a function

```
At /Users/jan/.atom/packages/atom-ide-hyperclick/node_modules/rxjs/util/subscribeToResult.js:43

TypeError: log4js is not a function
    at CatchSubscriber.selector (/packages/atom-ide-hyperclick/lib/HyperclickForTextEditor.js:307:17)
    at CatchSubscriber.error (/packages/atom-ide-hyperclick/node_modules/rxjs/operators/catchError.js:104:31)
    at MergeMapSubscriber.OuterSubscriber.notifyError (/packages/atom-ide-hyperclick/node_modules/rxjs/OuterSubscriber.js:22:26)
    at InnerSubscriber._error (/packages/atom-ide-hyperclick/node_modules/rxjs/InnerSubscriber.js:26:21)
    at InnerSubscriber.Subscriber.error (/packages/atom-ide-hyperclick/node_modules/rxjs/Subscriber.js:102:18)
    at DeferSubscriber.OuterSubscriber.notifyError (/packages/atom-ide-hyperclick/node_modules/rxjs/OuterSubscriber.js:22:26)
    at InnerSubscriber._error (/packages/atom-ide-hyperclick/node_modules/rxjs/InnerSubscriber.js:26:21)
    at InnerSubscriber.Subscriber.error (/packages/atom-ide-hyperclick/node_modules/rxjs/Subscriber.js:102:18)
    at /packages/atom-ide-hyperclick/node_modules/rxjs/util/subscribeToResult.js:40:48
```

### Non-Core Packages

```
atom-ide-hyperclick 1.0.0 
atom-shortcuts 0.0.2 
atomizr 0.23.2 
browse 2.6.2 
build 0.70.0 
build-fpc 0.1.1 
build-python 0.12.1 
console-panel 0.3.1 
edit-in-new-tab 0.11.0 
evaluate 0.10.0 
hopscotch 2.0.2 
hyperclick-nsis 0.8.0 
insert-nums 1.0.2 
language-babel 2.85.0 
language-ejs 0.4.0 
language-nsis 7.4.2 
language-nsl 4.1.1 
linter 2.3.1 
linter-makensis 0.14.1 
linter-ui-default 1.8.1 
local-storage 0.12.3 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
package-developer-toolbar 1.2.1 
package-settings 1.1.0 
portable-packages 0.3.3 
project-manager 3.3.8 
pynsist 0.11.0 
satisfy-dependencies 0.4.2 
script 3.26.0 
set-syntax 0.4.0 
timecop-2 0.3.3 
tool-bar 1.3.0 
trashman 0.2.0 
wordpress-salts 0.3.0 
```

**Comment by UziTech** [comment]
Thanks for reporting this. This should be fixed in the latest release (v1.0.2)
